#!/usr/bin/env bash
cd MAX
echo -e "\e[33m              _   _       _   __   _______\e[0m"
echo -e "\e[33m             |$| |$|     / \  \  \_/  / ____\e[0m"
echo -e "\e[33m            /  \_/  \   / * \  \  ♧ /____\e[0m"
echo -e "\e[33m           / / \_/ \ \ / ___ \ /  ♧ \___\e[0m"
echo -e "\e[33m          /_/       \ /_/   \_/_ /-\ _\__\e[0m"
while(true) do
lua start.lua 
done